services: 
  user_db:
    image: postgres:latest
    container_name: user_db
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes: 
      - user_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  user_service:
    image: ksushatarasova/user_service:latest
    container_name: user_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/user_db
    depends_on:
      - user_db

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
volumes:
  user_data:
  redis_data: