services: 
  user_db:
    image: postgres:latest
    container_name: user_db
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes: 
      - user_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  user_service:
    image: ksushatarasova/user_service:latest
    container_name: user_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/user_db
    depends_on:
      - user_db

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=user
      - SONAR_JDBC_PASSWORD=password
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      
  sonar_db:
    image: postgres:latest
    container_name: sonar_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonar_data:
  user_data:
  redis_data: